---
version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: sql_injection_mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./docker_etc/mysql_5.6/:/etc/mysql/
      - ./docker_etc/mysql_5.6/initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  mysql-data:
    driver: local
